#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

export EDITOR='vim'

HIST_STAMPS='yyyy-mm-dd'
export HISTTIMEFORMAT='-i '

# cd aliases.
# alias ..="cd .."
# alias ...="cd ../.."
# alias ....="cd ../../.."
# alias .....="cd ../../../.."
# alias ......="cd ../../../../.."

# alias updatedb='sudo /usr/libexec/locate.updatedb'

alias gist='gist -c -p -s'
alias grep='grep --exclude="*.egg/" --exclude="*.min.js"'
alias agrep="grep --color=auto -nr -A 2 -B 2"

alias docker-clean='docker rm `docker ps --no-trunc -aq` && docker images -q --filter "dangling=true" | xargs docker rmi'
alias asjson='python -m json.tool'
alias server='python3 -m http.server'

alias e=code
alias edit=code
alias c=code
alias download=aria2c
alias tf=terraform
alias kc=kubectl
alias kx=kubectx
alias kn=kubens

alias gssh='gcloud compute ssh'

export GOPATH=$HOME/go
export PATH=/usr/local/go/bin:$GOPATH/bin:$PATH

export PATH=$PATH:/usr/local/opt/dart/libexec
export PATH=$PATH:$HOME/.pub-cache-dart/bin

if [ -d $HOME/flutter ]; then
  # export PATH=$HOME/flutter/bin:$HOME/.pub-cache/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
  alias flutter="$HOME/flutter/bin/flutter"
fi

[ -d $HOME/android-tools ] && export PATH=$HOME/android-tools/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag --nocolor --ignore node_modules -g ""'

autoload -U colors; colors

# if [ -f ~/.kube/config ]; then
#   source $HOME/.zsh-kubectl-prompt/kubectl.zsh
#   RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
# fi
# export PATH=$HOME/.gloo/bin:$PATH

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Google Cloud SDK
if [ -f $HOME/google-cloud-sdk/path.zsh.inc ]; then
  source $HOME/google-cloud-sdk/path.zsh.inc
fi
if [ -f $HOME/google-cloud-sdk/completion.zsh.inc ]; then
  source $HOME/google-cloud-sdk/completion.zsh.inc
fi

# if [ -x /usr/local/bin/jenv ]; then
#   export PATH="$HOME/.jenv/bin:$PATH"
#   eval "$(jenv init -)"
#   export JAVA_HOME=$(jenv javahome);
# fi

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# For compilers to find zlib you may need to set:
export LDFLAGS="${LDFLAGS} -L/usr/local/opt/zlib/lib"
export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/zlib/include"

# For pkg-config to find zlib you may need to set:
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/zlib/lib/pkgconfig"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$HOME/.fastlane/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/berryp/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/berryp/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/berryp/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/berryp/google-cloud-sdk/completion.zsh.inc'; fi

export CLOUDSDK_PYTHON=$HOME/.pyenv/shims/python3
