#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

zstyle ':prezto:module:python:virtualenv' auto-switch 'yes'
zstyle ':prezto:module:python' skip-virtualenvwrapper-init 'on'

export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

export EDITOR='vim'

HIST_STAMPS='yyyy-mm-dd'
export HISTTIMEFORMAT='-i '

# cd aliases.
# alias ..="cd .."
# alias ...="cd ../.."
# alias ....="cd ../../.."
# alias .....="cd ../../../.."
# alias ......="cd ../../../../.."

# alias updatedb='sudo /usr/libexec/locate.updatedb'

alias gist='gist -c -p -s'
alias grep='grep --exclude="*.egg/" --exclude="*.min.js"'
alias agrep="grep --color=auto -nr -A 2 -B 2"

alias docker-clean='docker rm `docker ps --no-trunc -aq` && docker images -q --filter "dangling=true" | xargs docker rmi'
alias asjson='python -m json.tool'
alias server='python3 -m http.server'

alias e=code
alias edit=code
alias c=code
alias download=aria2c

# alias venv="pyenv virtualenv ${PWD##*/}"
# alias activate="pyenv activate ${PWD##*/}"

# export GPG_TTY=`tty`

# BASE16_SHELL=$HOME/.config/base16-shell/
# [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
# # Set the theme
# base16_tomorrow-night

source /opt/google-cloud-sdk/path.zsh.inc
alias gssh='gcloud compute ssh'

export GOPATH=$HOME/go
export PATH=/usr/local/go/bin:$GOPATH/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U colors; colors
source $HOME/.zsh-kubectl-prompt/kubectl.zsh
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
# export PATH=$HOME/.gloo/bin:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -f $HOME/google-cloud-sdk/path.zsh.inc ]; then source $HOME/google-cloud-sdk/path.zsh.inc; fi
if [ -f $HOME/google-cloud-sdk/completion.zsh.inc ]; then source $HOME/google-cloud-sdk/completion.zsh.inc; fi


if [ -x /usr/local/bin/jenv ]; then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
  export JAVA_HOME=dsds$(jenv javahome);
fi

# fpath=(/usr/local/share/zsh-completions $fpath)
# . /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# . /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# . /usr/local/share/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh

